#!/usr/bin/env bash

set -eu

APPDIR=$(readlink -f $(dirname "$APPDIR"))
SAVEDIR="${XDG_DATA_HOME:-~/.local/share}"/edge_of_solaris

mkdir -p "$SAVEDIR"
cd "$SAVEDIR"

for file in gamesave.json settings.json; do
    [ -f "$file" ] || cp "$APPDIR/$file" .
done

exec java                                   \
  -Djna.nosys=true                          \
  -Djava.library.path="$APPDIR:$APPDIR/lib" \
  -cp "$(printf %s: "$APPDIR"/lib/*.jar)"   \
  edge_of_solaris "$@"
